dist: trusty
services:
- docker
language: node_js
node_js:
- 8.4.0
env:
- TZ=America/New_York
script:
- npm run-script test-ci
branches:
  # We generally just care about PRs, but it's good to run on
  # the main branches so we know when the overall tree breaks.
  only:
  - master
  - develop
